language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_02c197307673_key -iv $encrypted_02c197307673_iv
  -in id_rsa2.enc -out ~/.ssh/id_rsa2 -d
- chmod 600 ~/.ssh/id_rsa2
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa2
- cp ssh_config ~/.ssh/config
- git config --global user.name "zchub"
- git config --global user.email "2368707467@qq.com"
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-generator-sitemap --save
- npm install hexo-deployer-git --save
script:
- hexo clean
- hexo g
- hexo d
