# Header
menu:
  Home: /
  Archives: /archives
  FE: /tags/front-end
  Note: /tags/随笔

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
# - tag
- tagcloud
- archive
- recent_posts

# 使用disqus，停止duoshuo
# duoshuo: wangxizhu

# disqus
disqus_shortname: zchub

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# baidu_tongji
baidu_tongji: true

# Miscellaneous
google_analytics: 
favicon: /img/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
